import { Metadata } from "next";

export const metadata: Metadata = {
  title: "CRYPTIQ | Login",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
